---

- name: debian | ubuntu | add java ppa repo
  apt_repository:
    repo: ppa:webupd8team/java
    state: present
  become: yes
#  when: ansible_distribution == 'Ubuntu'

- name: debian | set license as accepted
  debconf: name='oracle-java{{ oracle_java_version }}-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  become: yes


- name: debian | ensure Java is installed
  apt:
    name: "oracle-java{{ oracle_java_version }}-installer"
#    state={{ oracle_java_state }}
#    cache_valid_time={{ oracle_java_cache_valid_time }}
    update_cache: yes
  register: oracle_java_task_apt_install
  become: yes

- name: Print result
  debug:
    msg:
      - "{{ oracle_java_task_apt_install }}"


- name: debian | set Java version as default
  apt:
    name: "oracle-java{{ oracle_java_version }}-set-default"
    state: latest
  register: oracle_java_task_set_default
#  when: oracle_java_set_as_default
  become: yes

- name: Print result
  debug:
    msg:
      - "{{ oracle_java_task_set_default }}"


- name: Checking JAVA version
  shell: "java -version"
  become: no
  register: java_version_command_output

- name: Print result
  debug:
    msg:
#      - "{{ java_version_command_output }}"
      - "stderr {{ java_version_command_output.stderr_lines }}"
      - "stdout {{ java_version_command_output.stdout_lines }}"
#      - "stderr {{ oracle_java_task_set_default.results[0].stderr_lines }}"
#      - "stdout {{ oracle_java_task_set_default.results[0].stdout_lines }}"

#$ sudo apt install openjdk-8-jre
#$ sudo rm /etc/ssl/certs/java/cacerts
#$ sudo update-ca-certificates --fresh



#- name: Install  JAVA   packages
#  package:
#     use: apt
#     name: "{{ item }}"
#     state: latest
#  with_items:
##     - oracle-java9-set-default
#     - oracle-java8-set-default

